/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p9-g859cb6c9
 *
 * Project: 'h743_hal+h743_hal' 
 * Target:  'h743_hal' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32h7xx.h"



#endif /* RTE_COMPONENTS_H */
